INSERT INTO tb_category (name) VALUES ('Computadores e Notebooks');
INSERT INTO tb_category (name) VALUES ('Smartphones e Tablets');
INSERT INTO tb_category (name) VALUES ('Impressoras e Scanners');
INSERT INTO tb_category (name) VALUES ('Componentes e Peças');
INSERT INTO tb_category (name) VALUES ('Acessórios e Periféricos');
INSERT INTO tb_category (name) VALUES ('Armazenamento e Drives');
INSERT INTO tb_category (name) VALUES ('Monitores e Projetores');
INSERT INTO tb_category (name) VALUES ('Câmeras e Equipamentos de Vídeo');
INSERT INTO tb_category (name) VALUES ('Software e Licenças');
INSERT INTO tb_category (name) VALUES ('Redes e Conectividade');
INSERT INTO tb_category (name) VALUES ('Áudio e Microfones');
INSERT INTO tb_category (name) VALUES ('Teclados e Mouses');
INSERT INTO tb_category (name) VALUES ('Gabinetes e Fontes');
INSERT INTO tb_category (name) VALUES ('Placas de Vídeo');
INSERT INTO tb_category (name) VALUES ('Processadores');
INSERT INTO tb_category (name) VALUES ('Placas-mãe');
INSERT INTO tb_category (name) VALUES ('Memória RAM');
INSERT INTO tb_category (name) VALUES ('Coolers e Ventoinhas');
INSERT INTO tb_category (name) VALUES ('Cabos e Adaptadores');
INSERT INTO tb_category (name) VALUES ('Baterias e Carregadores');
