INSERT INTO tb_category (name, created_at) VALUES ('Computadores e Notebooks', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Smartphones e Tablets', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Impressoras e Scanners', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Componentes e Peças', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Acessórios e Periféricos', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Armazenamento e Drives', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Monitores e Projetores', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Câmeras e Equipamentos de Vídeo', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Software e Licenças', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Redes e Conectividade', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Áudio e Microfones', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Teclados e Mouses', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Gabinetes e Fontes', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Placas de Vídeo', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Processadores', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Placas-mãe', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Memória RAM', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Coolers e Ventoinhas', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Cabos e Adaptadores', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Baterias e Carregadores', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Computadores e Notebooks', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Smartphones e Tablets', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Impressoras e Scanners', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Componentes e Peças', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Acessórios e Periféricos', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Armazenamento e Drives', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Monitores e Projetores', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Câmeras e Equipamentos de Vídeo', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Software e Licenças', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Redes e Conectividade', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Áudio e Microfones', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Teclados e Mouses', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Gabinetes e Fontes', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Placas de Vídeo', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Processadores', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Placas-mãe', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Memória RAM', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Coolers e Ventoinhas', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Cabos e Adaptadores', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Baterias e Carregadores', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Web Design', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Marketing Digital', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Desenvolvimento Mobile', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Design Gráfico', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Banco de Dados', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Programação Web', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Desenvolvimento de Jogos', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Inteligência Artificial', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('IoT - Internet das Coisas', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Machine Learning', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Redes Neurais', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Engenharia de Software', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Segurança da Informação', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Sistemas Embarcados', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Robótica', NOW());
